# fly.toml app configuration file generated for rust-zerotoprod on 2023-12-27T22:29:38+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rust-zerotoprod"
primary_region = "sin"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
