application:
  port: 8000
  base_url: "http://127.0.0.1:8000"
  hmac_secret: "my-secret"
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
telemetry:
  enabled: false
  api_key: "my-honeycomb-api-key"
  endpoint: "https://api.honeycomb.io:443"
email:
  endpoint: https://api.sendinblue.com
  api_key: "my-email-api-key"
  sender:
    name: "Pranitha"
    email: "sender@email.com"
  timeout_millis: 10000
