application:
  port: 8000
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
telemetry:
  api_key: "" # Add your honeycomb.io api key here
  endpoint: "https://api.honeycomb.io:443"
